return {
	placeholders = { "{選択した文字列}", "{TEXT}" },
	defaultTemplateUrl = "https://chatgpt.com/?q={TEXT}",
	defaultQueryTemplate = "{TEXT}",
	templateModelOptions = { "gpt-4o", "o3", "gpt-5", "gpt-5-thinking", "custom" },
	defaultHardLimit = 3000,
	defaultParentMenuTitle = "ChatGPTで検索",
	defaultTemplates = {
		{
			id = "template-1",
			label = "標準検索",
			url = "https://chatgpt.com/?q={TEXT}",
			queryTemplate = "{TEXT}",
			enabled = true,
			hintsSearch = false,
			temporaryChat = false,
			model = "gpt-5",
		},
		{
			id = "template-2",
			label = "Search + Temporary",
			url = "https://chatgpt.com/?q={TEXT}",
			queryTemplate = "{TEXT}",
			enabled = false,
			hintsSearch = true,
			temporaryChat = true,
			model = "gpt-5-thinking",
		},
	},
}
